<?php
declare(strict_types=1);

return [
    'start' => [
        'title' => 'UniSurf - Unique Surfing',
        'description' => 'UniSurf bietet Services für einzigartige Ideen: Webentwicklung, Hosting und digitale Lösungen für Ihr Unternehmen.',
        'keywords' => 'UniSurf, Webentwicklung, Web-Hosting, Internetseiten, Webshops, Portale, Plattformen',
        'cms' => true,
        'nav' => false,
        'nav_label' => 'Start',
        'nav_order' => 10,
        'canonical' => '/',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/start.jpg',
    ],
    'services' => [
        'title' => 'Services',
        'description' => 'Unsere Services: Webentwicklung, Hosting und digitale Lösungen für Ihr Unternehmen.',
        'keywords' => 'Services, Webentwicklung, Hosting, E-Commerce, Portale',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Services',
        'nav_order' => 20,
        'canonical' => '/services',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/services.jpg',
    ],
    'entwicklung' => [
        'title' => 'Entwicklung',
        'description' => 'Professionelle Webentwicklung: Internetseiten, Webshops, Portale und skalierbare Plattformen.',
        'keywords' => 'Webentwicklung, Internetseiten, Webshops, Portale, E-Commerce, Plattformen',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Entwicklung',
        'nav_order' => 30,
        'canonical' => '/entwicklung',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/entwicklung.jpg',
    ],
    'hosting' => [
        'title' => 'Hosting',
        'description' => 'Professionelles Web-Hosting: Cloud-basiert, sicher und zuverlässig mit individueller Betreuung.',
        'keywords' => 'Web-Hosting, Cloud-Hosting, Server, Infrastruktur, Sicherheit',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Hosting',
        'nav_order' => 40,
        'canonical' => '/hosting',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/hosting.jpg',
    ],
    'impressum' => [
        'title' => 'Impressum',
        'description' => 'Impressum und rechtliche Angaben von UniSurf.',
        'keywords' => 'Impressum, Anbieterkennzeichnung, Rechtliche Angaben',
        'cms' => true,
        'nav' => false,
        'nav_label' => 'Impressum',
        'nav_order' => 90,
        'canonical' => '/impressum',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/impressum.jpg',
    ],
    'datenschutz' => [
        'title' => 'Datenschutzerklärung',
        'description' => 'Datenschutzerklärung: Informationen zur Verarbeitung personenbezogener Daten (DSGVO).',
        'keywords' => 'Datenschutzerklärung, DSGVO, Datenschutz, personenbezogene Daten',
        'cms' => true,
        'nav' => false,
        'nav_label' => 'Datenschutz',
        'nav_order' => 100,
        'canonical' => '/datenschutz',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/datenschutz.jpg',
    ],
];
